version: '3'
services:
  react-nginx:
    image: trzl/portfolio:fotomatic-react.1
    restart: unless-stopped
    container_name: fotomatic-nginx
    networks:
      - fotomatic
    env_file: .env
    environment:
      - NODE_ENV=production
  reverseproxy:
    image: trzl/portfolio:fotomatic-proxy.1
    container_name: fotomatic-proxy
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    depends_on:
      - react-nginx
   environment:
      VIRTUAL_HOST: fotomatic.tbrownkcdev.com
      LETSENCRYPT_HOST: fotomatic.tbrownkcdev.com
      LETSENCRYPT_EMAIL: brownty47@gmail.com
networks:
  default:
    external:
      name: webproxy
  fotomatic:
    driver: bridge